version: '3.4'

services:
    www:
        build: www
        working_dir: /var/www/current
        depends_on:
            - mysql
        ports:
            - ${WWW_PORT}:80
        volumes:
            - ../:/var/www/current
            - ./www/nginx/sites-available/:/etc/nginx/sites-available/
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SF_DATABASE_HOST: mysql
            SF_DATABASE_PORT: 3306
            SF_DATABASE_NAME: sidus_datagrid
            SF_DATABASE_USER: sidus_datagrid
            SF_DATABASE_PASSWORD: sidus_datagrid
            SF_SECRET: 62dc728d9c9976def108065bd8907d2b4dce07ed
            SF_TRUSTED_PROXIES: '~'
            COMPOSER_MEMORY_LIMIT: -1

    mysql:
        image: mariadb
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: sidus_datagrid
            MYSQL_USER: sidus_datagrid
            MYSQL_PASSWORD: sidus_datagrid

volumes:
    mysql_data: ~
